import { chromium,request } from '@playwright/test';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1100}});const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
 await page.goto(base,{waitUntil:'networkidle'});await page.getByRole('heading',{name:/Good morning/}).waitFor();await page.screenshot({path:'/tmp/bloom-desktop.png',fullPage:true});
 const date=await page.getByLabel('Diary date').inputValue();const response=await context.request.get(`${base}/api/tracker?date=${date}`);assert.equal(response.status(),200);const first=await response.json();assert.equal(first.demo,true,'Run against an unconfigured local demo only');assert.equal(first.foods.length,5);
 await page.getByRole('button',{name:'Add food',exact:true}).click();await page.getByRole('tab',{name:'Manual',exact:true}).click();await page.getByLabel('Food name',{exact:true}).fill('Browser test oatmeal');await page.getByLabel('Calories (kcal)',{exact:true}).fill('100');await page.getByLabel('Protein (g)',{exact:true}).fill('10');await page.getByLabel('Carbs (g)',{exact:true}).fill('15');await page.getByLabel('Fat (g)',{exact:true}).fill('2');await page.getByLabel('Portion in grams',{exact:true}).fill('200');await page.getByRole('button',{name:'Confirm & add food'}).click();await page.getByText('Browser test oatmeal',{exact:true}).waitFor();
 const after=await (await context.request.get(`${base}/api/tracker?date=${date}`)).json();const food=after.foods.find(f=>f.name==='Browser test oatmeal');assert.equal(food.calories,200);assert.equal(food.protein,20);
 const other=await request.newContext({baseURL:base});await other.get(`/api/tracker?date=${date}`);const denied=await other.delete('/api/tracker',{headers:{'X-Requested-With':'bloom','Origin':base},data:{resource:'food',id:food.id}});assert.equal(denied.status(),404,'Cross-session deletion must fail');await other.dispose();
 const csrf=await context.request.post(`${base}/api/tracker`,{headers:{Origin:'https://attacker.invalid','X-Requested-With':'bloom'},data:{resource:'water',date,data:{amount:0}}});assert.equal(csrf.status(),403);
 const invalid=await context.request.post(`${base}/api/tracker`,{headers:{'X-Requested-With':'bloom'},data:{resource:'food',date,data:{name:'Invalid'}}});assert.equal(invalid.status(),400);
 await page.getByRole('button',{name:/Add water/}).click();await page.waitForTimeout(500);const hydrated=await (await context.request.get(`${base}/api/tracker?date=${date}`)).json();assert.equal(hydrated.water,1750);
 await page.getByText('Browser test oatmeal',{exact:true}).click();await page.getByLabel('Portion in grams',{exact:true}).fill('150');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('Meal updated. Looking good.').waitFor();const edited=await (await context.request.get(`${base}/api/tracker?date=${date}`)).json();assert.equal(edited.foods.find(f=>f.id===food.id).calories,150);
 await page.getByText('Browser test oatmeal',{exact:true}).click();await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Confirm delete',exact:true}).click();await page.getByText('Food removed from your diary.').waitFor();assert.equal(await page.getByText('Browser test oatmeal',{exact:true}).count(),0);
 await page.getByRole('button',{name:'Edit targets',exact:true}).click();await page.getByLabel('Calories (kcal)',{exact:true}).fill('2300');await page.getByRole('button',{name:'Save my targets'}).click();await page.getByText('Your daily targets are updated.').waitFor();assert.equal((await (await context.request.get(`${base}/api/tracker?date=${date}`)).json()).targets.calories,2300);
 await page.getByRole('button',{name:'Workouts',exact:true}).click();await page.getByRole('button',{name:'Log workout',exact:true}).click();await page.getByRole('button',{name:'Finish & log workout'}).click();await page.getByText('You showed up. Workout logged.').waitFor();assert.equal((await (await context.request.get(`${base}/api/tracker?date=${date}`)).json()).workouts.length,1);
 await page.getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('button',{name:'Previous day',exact:true}).click();await page.waitForTimeout(500);assert.equal(await page.getByText('Avocado toast & eggs',{exact:true}).count(),0);await page.getByRole('button',{name:'Next day',exact:true}).click();await page.getByText('Avocado toast & eggs',{exact:true}).waitFor();
 const protectedAI=await context.request.post(`${base}/api/estimate`,{headers:{'X-Requested-With':'bloom'}});assert.equal(protectedAI.status(),401);
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.screenshot({path:'/tmp/bloom-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile should not overflow');await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'Community',exact:false}).click();await page.getByRole('heading',{name:'Healthy habits grow together.'}).waitFor();
 assert.deepEqual(errors,[],'No browser runtime/hydration errors');console.log('PASS: UI diary CRUD, portions, hydration, targets, workouts, date switching, CSRF, IDOR, invalid input, protected AI, dialog Escape, mobile layout, community.');
}finally{await browser.close();}
