import { z } from 'zod';
import { db } from '@/db';
import { pushSubscriptions } from '@/db/schema';
import { eq,and,sql } from 'drizzle-orm';
import { identity,body,json,failure,limit } from '@/lib/security';
export const endpointSchema=z.string().url().max(2048).refine(value=>{const u=new URL(value);return u.protocol==='https:'&&(!u.port||u.port==='443')&&!u.username&&!u.password&&(['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].includes(u.hostname)||u.hostname.endsWith('.push.apple.com')||u.hostname.endsWith('.notify.windows.com'));},'Unsupported push provider');
export async function GET(req:Request){try{await identity(req,true);z.object({}).strict().parse(Object.fromEntries(new URL(req.url).searchParams));return json({publicKey:process.env.VAPID_PUBLIC_KEY||null});}catch(e){return failure(e);}}
export async function POST(req:Request){try{const user=await identity(req,true);await limit(`push:${user.id}`,10);const data=await body(req,z.object({endpoint:endpointSchema,expirationTime:z.number().nullable().optional(),keys:z.object({p256dh:z.string().regex(/^[\w-]+$/).min(80).max(120),auth:z.string().regex(/^[\w-]+$/).min(20).max(40)}).strict()}).strict());await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${user.id+'push'}))`);await tx.delete(pushSubscriptions).where(and(eq(pushSubscriptions.userId,user.id),sql`${pushSubscriptions.data}->>'endpoint' = ${data.endpoint}`));await tx.insert(pushSubscriptions).values({userId:user.id,date:new Date().toISOString().slice(0,10),data});});return json({ok:true},201);}catch(e){return failure(e);}}
export async function DELETE(req:Request){try{const user=await identity(req,true);await limit(`push:${user.id}`,10);const {endpoint}=await body(req,z.object({endpoint:endpointSchema}).strict());await db.delete(pushSubscriptions).where(and(eq(pushSubscriptions.userId,user.id),sql`${pushSubscriptions.data}->>'endpoint' = ${endpoint}`));return json({ok:true});}catch(e){return failure(e);}}
