export const initialFoods = [
 {name:'Avocado toast & eggs',meal:'Breakfast',serving:'2 slices · 2 eggs',grams:250,calories:420,protein:22,carbs:38,fat:20,image:'https://images.pexels.com/photos/793782/pexels-photo-793782.jpeg?auto=compress&cs=tinysrgb&w=120&h=120&fit=crop'},
 {name:'Greek yogurt & blueberries',meal:'Breakfast',serving:'1 bowl · 200 g',grams:200,calories:180,protein:18,carbs:22,fat:2,image:'https://images.pexels.com/photos/765548/pexels-photo-765548.jpeg?auto=compress&cs=tinysrgb&w=120&h=120&fit=crop'},
 {name:'Grilled chicken nourish bowl',meal:'Lunch',serving:'1 bowl · 350 g',grams:350,calories:560,protein:48,carbs:58,fat:15,image:'https://images.pexels.com/photos/105588/pexels-photo-105588.jpeg?auto=compress&cs=tinysrgb&w=120&h=120&fit=crop'},
 {name:'Banana & almond butter',meal:'Snacks',serving:'1 medium · 1 tbsp',grams:150,calories:260,protein:8,carbs:35,fat:12,image:null},
 {name:'Flat white',meal:'Snacks',serving:'1 cup · 180 ml',grams:180,calories:120,protein:8,carbs:11,fat:5,image:null}
];
export const defaultTargets={calories:2200,protein:140,carbs:250,fat:70,water:2500};
export const drinkLibrary=[
 {name:'Water',calories:0,protein:0,carbs:0,fat:0,drinkType:'water'},
 {name:'Sparkling Water',calories:0,protein:0,carbs:0,fat:0,drinkType:'water'},
 {name:'Electrolyte Water',calories:0,protein:0,carbs:0,fat:0,drinkType:'water'},
 {name:'Coca-Cola Original',calories:42,protein:0,carbs:10.6,fat:0,drinkType:'soda'},
 {name:'Coca-Cola Zero Sugar',calories:0,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'Diet Coke',calories:0,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'Coca-Cola Cherry',calories:43,protein:0,carbs:10.8,fat:0,drinkType:'soda'},
 {name:'Coca-Cola Vanilla',calories:43,protein:0,carbs:10.8,fat:0,drinkType:'soda'},
 {name:'Pepsi',calories:44,protein:0,carbs:11.0,fat:0,drinkType:'soda'},
 {name:'Diet Pepsi',calories:0,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'Pepsi Zero Sugar',calories:0,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'Dr Pepper',calories:42,protein:0,carbs:11.0,fat:0,drinkType:'soda'},
 {name:'Dr Pepper Zero Sugar',calories:0,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'Sprite',calories:39,protein:0,carbs:9.6,fat:0,drinkType:'soda'},
 {name:'Sprite Zero Sugar',calories:1,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'Fanta Orange',calories:48,protein:0,carbs:12.0,fat:0,drinkType:'soda'},
 {name:'Mountain Dew',calories:46,protein:0,carbs:12.0,fat:0,drinkType:'soda'},
 {name:'Mountain Dew Zero Sugar',calories:0,protein:0,carbs:0,fat:0,drinkType:'soda'},
 {name:'7UP',calories:41,protein:0,carbs:10.8,fat:0,drinkType:'soda'},
 {name:'A&W Root Beer',calories:45,protein:0,carbs:12.0,fat:0,drinkType:'soda'},
 {name:'Canada Dry Ginger Ale',calories:40,protein:0,carbs:10.5,fat:0,drinkType:'soda'},
 {name:'Mexican Coca-Cola',calories:42,protein:0,carbs:10.6,fat:0,drinkType:'soda'},
 {name:'Jarritos Mandarin',calories:45,protein:0,carbs:11.0,fat:0,drinkType:'soda'},
 {name:'Jarritos Tamarind',calories:45,protein:0,carbs:11.0,fat:0,drinkType:'soda'},
 {name:'Jarritos Fruit Punch',calories:45,protein:0,carbs:11.0,fat:0,drinkType:'soda'},
 {name:'Monster Energy Original',calories:47,protein:0,carbs:11.5,fat:0,drinkType:'energy'},
 {name:'Monster Zero Sugar',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Monster Ultra White',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Monster Ultra Sunrise',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Monster Ultra Paradise',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Monster Ultra Strawberry Dreams',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Monster Mango Loco',calories:50,protein:0,carbs:12.0,fat:0,drinkType:'energy'},
 {name:'Monster Pipeline Punch',calories:48,protein:0,carbs:12.0,fat:0,drinkType:'energy'},
 {name:'Monster Pacific Punch',calories:48,protein:0,carbs:12.0,fat:0,drinkType:'energy'},
 {name:'Red Bull Energy Drink',calories:46,protein:0,carbs:11.0,fat:0,drinkType:'energy'},
 {name:'Red Bull Sugarfree',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Red Bull Zero',calories:3,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Red Bull Red Edition',calories:46,protein:0,carbs:11.0,fat:0,drinkType:'energy'},
 {name:'Red Bull Blue Edition',calories:46,protein:0,carbs:11.0,fat:0,drinkType:'energy'},
 {name:'Red Bull Yellow Edition',calories:46,protein:0,carbs:11.0,fat:0,drinkType:'energy'},
 {name:'Celsius',calories:4,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Celsius Vibe',calories:4,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Alani Nu Energy',calories:4,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'GHOST Energy',calories:4,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Rockstar Energy Drink',calories:47,protein:0,carbs:12.0,fat:0,drinkType:'energy'},
 {name:'Bang Energy',calories:0,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Prime Energy',calories:4,protein:0,carbs:0,fat:0,drinkType:'energy'},
 {name:'Prime Hydration',calories:5,protein:0,carbs:1.0,fat:0,drinkType:'sports'},
 {name:'Gatorade Original',calories:24,protein:0,carbs:6.0,fat:0,drinkType:'sports'},
 {name:'Gatorade Zero',calories:1,protein:0,carbs:0,fat:0,drinkType:'sports'},
 {name:'Gatorade Fit',calories:10,protein:0,carbs:2.0,fat:0,drinkType:'sports'},
 {name:'Powerade Mountain Berry Blast',calories:20,protein:0,carbs:5.0,fat:0,drinkType:'sports'},
 {name:'Powerade Zero',calories:0,protein:0,carbs:0,fat:0,drinkType:'sports'},
 {name:'BODYARMOR Sports Drink',calories:25,protein:0,carbs:6.0,fat:0,drinkType:'sports'},
 {name:'BODYARMOR Lyte',calories:10,protein:0,carbs:2.0,fat:0,drinkType:'sports'},
 {name:'Liquid I.V. Hydration Drink',calories:20,protein:0,carbs:5.0,fat:0,drinkType:'sports'},
 {name:'Milk, Whole',calories:61,protein:3.2,carbs:4.8,fat:3.3,drinkType:'milk'},
 {name:'Milk, 2%',calories:50,protein:3.3,carbs:4.8,fat:2,drinkType:'milk'},
 {name:'Milk, 1%',calories:42,protein:3.4,carbs:5.0,fat:1,drinkType:'milk'},
 {name:'Milk, Skim',calories:34,protein:3.4,carbs:5.0,fat:0.1,drinkType:'milk'},
 {name:'Chocolate Milk',calories:80,protein:3.3,carbs:12.0,fat:2.5,drinkType:'milk'},
 {name:'Almond Milk, Unsweetened',calories:15,protein:0.6,carbs:0.6,fat:1.2,drinkType:'milk'},
 {name:'Almond Milk, Sweetened',calories:24,protein:0.5,carbs:3.5,fat:1.0,drinkType:'milk'},
 {name:'Oat Milk',calories:46,protein:1.0,carbs:6.7,fat:1.5,drinkType:'milk'},
 {name:'Soy Milk',calories:41,protein:3.3,carbs:3.3,fat:1.9,drinkType:'milk'},
 {name:'Coconut Milk Beverage',calories:19,protein:0.2,carbs:1.0,fat:1.5,drinkType:'milk'},
 {name:'Lactose-Free Milk',calories:50,protein:3.3,carbs:4.8,fat:2,drinkType:'milk'},
 {name:'Orange Juice',calories:45,protein:0.7,carbs:10.4,fat:0.2,drinkType:'juice'},
 {name:'Apple Juice',calories:46,protein:0.1,carbs:11.3,fat:0.1,drinkType:'juice'},
 {name:'Grape Juice',calories:61,protein:0.4,carbs:15.0,fat:0.1,drinkType:'juice'},
 {name:'Cranberry Juice Cocktail',calories:46,protein:0,carbs:12.0,fat:0,drinkType:'juice'},
 {name:'Lemonade',calories:40,protein:0,carbs:10.0,fat:0,drinkType:'juice'},
 {name:'Simply Orange',calories:45,protein:0.7,carbs:10.4,fat:0.2,drinkType:'juice'},
 {name:'Tropicana Orange Juice',calories:45,protein:0.7,carbs:10.4,fat:0.2,drinkType:'juice'},
 {name:'Naked Green Machine',calories:55,protein:0,carbs:13.0,fat:0,drinkType:'juice'},
 {name:'Coffee, Black',calories:2,protein:0.3,carbs:0,fat:0,drinkType:'coffee'},
 {name:'Cold Brew Coffee, Black',calories:1,protein:0.1,carbs:0,fat:0,drinkType:'coffee'},
 {name:'Iced Coffee, Sweetened',calories:40,protein:0.5,carbs:8.0,fat:0.5,drinkType:'coffee'},
 {name:'Latte, 2% Milk',calories:50,protein:3.0,carbs:5.0,fat:2.0,drinkType:'coffee'},
 {name:'Cappuccino, 2% Milk',calories:45,protein:3.0,carbs:4.0,fat:2.0,drinkType:'coffee'},
 {name:'Starbucks Frappuccino Bottled Coffee',calories:60,protein:2,carbs:10,fat:1.5,drinkType:'coffee'},
 {name:'Horchata',calories:100,protein:1,carbs:18,fat:2,drinkType:'juice'},
 {name:'Agua Fresca',calories:35,protein:0,carbs:8.5,fat:0,drinkType:'juice'},
 {name:'Jamaica Agua Fresca',calories:35,protein:0,carbs:8.5,fat:0,drinkType:'juice'},
 {name:'Tamarindo Agua Fresca',calories:45,protein:0,carbs:11,fat:0,drinkType:'juice'},
 {name:'Rompope',calories:220,protein:4,carbs:20,fat:12,drinkType:'alcohol'},
 {name:'Eggnog',calories:135,protein:5,carbs:20,fat:4.5,drinkType:'alcohol'},
 {name:'Margarita, Prepared',calories:130,protein:0,carbs:14,fat:0,drinkType:'alcohol'},
 {name:'Beer, Lager',calories:43,protein:0.5,carbs:3.5,fat:0,drinkType:'alcohol'},
 {name:'Wine, Red',calories:85,protein:0.1,carbs:2.6,fat:0,drinkType:'alcohol'},
 {name:'Wine, White',calories:82,protein:0.1,carbs:2.6,fat:0,drinkType:'alcohol'},
];
export const library=[{name:'Chicken breast, grilled',calories:165,protein:31,carbs:0,fat:3.6},{name:'Brown rice, cooked',calories:123,protein:2.7,carbs:25.6,fat:1},{name:'Avocado',calories:160,protein:2,carbs:8.5,fat:14.7},{name:'Greek yogurt, plain',calories:59,protein:10,carbs:3.6,fat:0.4},{name:'Banana',calories:89,protein:1.1,carbs:22.8,fat:0.3},{name:'Oats',calories:389,protein:16.9,carbs:66.3,fat:6.9},{name:'Salmon, cooked',calories:206,protein:22,carbs:0,fat:12},{name:'Egg, whole',calories:155,protein:13,carbs:1.1,fat:11}];
