import { timingSafeEqual } from 'crypto';
import webpush from 'web-push';
import { z } from 'zod';
import { eq,sql,lt } from 'drizzle-orm';
import { db } from '@/db';
import { supplementSchedules,pushSubscriptions,rateLimits,foodsCache } from '@/db/schema';
import { json,failure,ApiError } from '@/lib/security';
import { endpointSchema } from '@/app/api/push/route';
export const runtime='nodejs';export const maxDuration=60;
export async function GET(req:Request){try{z.object({}).strict().parse(Object.fromEntries(new URL(req.url).searchParams));const expected=`Bearer ${process.env.CRON_SECRET||''}`;const provided=req.headers.get('authorization')||'';if(!process.env.CRON_SECRET||expected.length!==provided.length||!timingSafeEqual(Buffer.from(expected),Buffer.from(provided)))throw new ApiError(401,'Unauthorized.');await db.delete(rateLimits).where(lt(rateLimits.expiresAt,new Date()));await db.delete(foodsCache).where(lt(foodsCache.expiresAt,new Date()));if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY||!process.env.VAPID_SUBJECT)return json({ok:true,sent:0,status:'Push is not configured.'});webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);let sent=0;const deadline=Date.now()+45000;const due=await db.select().from(supplementSchedules).where(sql`${supplementSchedules.data}->>'enabled'='true' AND ${supplementSchedules.data}->>'nextAt' <= ${new Date().toISOString()}`).limit(40);
 for(const schedule of due){if(Date.now()>deadline)break;const parsed=z.object({name:z.string().max(100),nextAt:z.string().datetime(),intervalHours:z.number().int().min(1).max(168)}).safeParse(schedule.data);if(!parsed.success)continue;const old=parsed.data.nextAt;const nextAt=new Date(Date.now()+parsed.data.intervalHours*3600000).toISOString();const claimed=await db.update(supplementSchedules).set({data:{...schedule.data,nextAt}}).where(sql`${supplementSchedules.id}=${schedule.id} AND ${supplementSchedules.data}->>'nextAt'=${old}`).returning();if(!claimed.length)continue;const subs=await db.select().from(pushSubscriptions).where(eq(pushSubscriptions.userId,schedule.userId)).limit(5);for(const sub of subs){const parsedSub=z.object({endpoint:endpointSchema,keys:z.object({p256dh:z.string(),auth:z.string()})}).safeParse(sub.data);if(!parsedSub.success)continue;try{await webpush.sendNotification(parsedSub.data,JSON.stringify({title:'A little moment for you.',body:'Your daily check-in is ready. Open Bloom when you have a moment.'}),{TTL:3600,timeout:3500});sent++;}catch(e){const status=(e as {statusCode?:number}).statusCode;if(status===410||status===404)await db.delete(pushSubscriptions).where(eq(pushSubscriptions.id,sub.id));}}}
 await db.delete(rateLimits).where(lt(rateLimits.expiresAt,new Date()));await db.delete(foodsCache).where(lt(foodsCache.expiresAt,new Date()));return json({ok:true,sent});}catch(e){return failure(e);}}
