import { db } from '@/db';
import { foodLogs,profiles,trackerRecords,supplements,supplementLogs,workoutSessions,workouts,customFoods,supplementSchedules } from '@/db/schema';
import { and,eq,sql,desc } from 'drizzle-orm';
import { z } from 'zod';
import { identity,json,failure,body,foodSchema,dateSchema,limit,audit,ApiError } from '@/lib/security';
import { defaultTargets } from '@/lib/demo';
const tables={water:trackerRecords,supplement:supplements,supplementLog:supplementLogs,workout:workoutSessions,template:workouts,custom:customFoods,schedule:supplementSchedules};
const targets=z.object({calories:z.number().min(500).max(10000),protein:z.number().min(10).max(500),carbs:z.number().min(0).max(1000),fat:z.number().min(10).max(300),water:z.number().min(250).max(10000)}).strict();
const set=z.object({exercise:z.string().trim().min(1).max(100),sets:z.number().int().min(1).max(50),reps:z.number().int().min(1).max(1000),weight:z.number().min(0).max(1000),rpe:z.number().min(1).max(10)});
const entitySchema=z.discriminatedUnion('resource',[
 z.object({resource:z.literal('water'),data:z.object({amount:z.number().int().min(0).max(15000)})}),
 z.object({resource:z.literal('waterAdd'),data:z.object({amount:z.number().int().min(1).max(5000)})}),
 z.object({resource:z.literal('supplement'),data:z.object({name:z.string().trim().min(1).max(100),dose:z.string().trim().min(1).max(80),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),notes:z.string().max(500).default(''),timezone:z.string().min(1).max(80).optional()})}),
 z.object({resource:z.literal('supplementLog'),data:z.object({supplementId:z.string().uuid(),name:z.string().max(100),dose:z.string().max(80),time:z.string().max(40),notes:z.string().max(500).default('')})}),
 z.object({resource:z.literal('workout'),data:z.object({name:z.string().trim().min(1).max(100),duration:z.number().min(1).max(600),exercises:z.array(set).min(1).max(50),notes:z.string().max(1000).default('')})}),
 z.object({resource:z.literal('template'),data:z.object({name:z.string().trim().min(1).max(100),exercises:z.array(set).min(1).max(50)})}),
 z.object({resource:z.literal('custom'),data:z.object({name:z.string().trim().min(1).max(150),calories:z.number().min(0).max(1000),protein:z.number().min(0).max(100),carbs:z.number().min(0).max(100),fat:z.number().min(0).max(100)})}),
 z.object({resource:z.literal('schedule'),data:z.object({name:z.string().min(1).max(100),dose:z.string().max(80).optional(),time:z.string().regex(/^([01]\\d|2[0-3]):[0-5]\\d$/),timezone:z.string().min(1).max(80),nextAt:z.string().datetime(),enabled:z.boolean(),intervalHours:z.number().int().min(1).max(168),supplementId:z.string().uuid().optional()})})
]);
export async function GET(req:Request){try{
 const user=await identity(req);await limit(`read:${user.id}`,120);
 const q=z.object({date:dateSchema}).strict().parse(Object.fromEntries(new URL(req.url).searchParams));
 await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${user.id}))`);const existing=await tx.select().from(profiles).where(eq(profiles.userId,user.id)).limit(1);if(!existing.length){await tx.insert(profiles).values({userId:user.id,date:q.date,data:{...defaultTargets,name:'You',username:((user.email||'bloommember').split('@')[0].replace(/[^a-zA-Z0-9_.-]/g,'').slice(0,17)||'bloommember').concat('_',user.id.replace(/-/g,'').slice(-6))}});}});
 const [foods,profile,water,supps,taken,sessions,templates,history,waterHistory]=await Promise.all([
 db.select().from(foodLogs).where(and(eq(foodLogs.userId,user.id),eq(foodLogs.date,q.date))).orderBy(foodLogs.createdAt),db.select().from(profiles).where(eq(profiles.userId,user.id)).limit(1),db.select().from(trackerRecords).where(and(eq(trackerRecords.userId,user.id),eq(trackerRecords.date,q.date))).orderBy(desc(trackerRecords.createdAt)).limit(1),db.select().from(supplements).where(eq(supplements.userId,user.id)).limit(100),db.select().from(supplementLogs).where(and(eq(supplementLogs.userId,user.id),eq(supplementLogs.date,q.date))),db.select().from(workoutSessions).where(eq(workoutSessions.userId,user.id)).orderBy(desc(workoutSessions.createdAt)).limit(100),db.select().from(workouts).where(eq(workouts.userId,user.id)).limit(100),db.select().from(foodLogs).where(and(eq(foodLogs.userId,user.id),sql`${foodLogs.date} >= ${new Date(Date.parse(q.date)-6*86400000).toISOString().slice(0,10)}`,sql`${foodLogs.date} <= ${q.date}`)),db.select().from(trackerRecords).where(and(eq(trackerRecords.userId,user.id),sql`${trackerRecords.date} >= ${new Date(Date.parse(q.date)-6*86400000).toISOString().slice(0,10)}`,sql`${trackerRecords.date} <= ${q.date}`)).orderBy(trackerRecords.date)]);
 return json({foods,targets:profile[0]?.data||defaultTargets,username:typeof profile[0]?.data?.username==='string'?profile[0].data.username:'',water:water[0]?.data.amount||0,supplements:supps,taken,workouts:sessions,templates,history,waterHistory:waterHistory.map(r=>({date:r.date,amount:Number(r.data?.amount||0)}))});
}catch(e){return failure(e);}}
export async function POST(req:Request){try{
 const user=await identity(req);await limit(`write:${user.id}`);const input=await body(req,z.object({resource:z.string(),date:dateSchema,data:z.unknown(),id:z.string().uuid().optional()}).strict());
 if(input.resource==='food'){const data=foodSchema.parse({...input.data as object,date:input.date});if(input.id){const [row]=await db.update(foodLogs).set(data).where(and(eq(foodLogs.id,input.id),eq(foodLogs.userId,user.id))).returning();if(!row)throw new ApiError(404,'Entry not found.');return json(row);}const [row]=await db.insert(foodLogs).values({...data,userId:user.id}).returning();await audit(user.id,'food.created');return json(row,201);}
 if(input.resource==='targets'){const data=targets.parse(input.data);const [p]=await db.select().from(profiles).where(eq(profiles.userId,user.id)).limit(1);await db.update(profiles).set({data:{...(p?.data||{}),...data}}).where(eq(profiles.userId,user.id));return json({ok:true});} if(input.resource==='username'){const data=z.object({username:z.string().trim().min(3).max(24).regex(/^[a-zA-Z0-9_.-]+$/)}).strict().parse(input.data);const [taken]=await db.select({userId:profiles.userId}).from(profiles).where(and(sql`lower(${profiles.data}->>'username') = lower(${data.username})`,sql`${profiles.userId} <> ${user.id}`)).limit(1);if(taken)throw new ApiError(409,'That username is already taken.');const [p]=await db.select().from(profiles).where(eq(profiles.userId,user.id)).limit(1);if(!p)throw new ApiError(404,'Your Bloom profile is not ready yet.');await db.update(profiles).set({data:{...p.data,username:data.username}}).where(eq(profiles.userId,user.id));return json({ok:true,username:data.username});}
 const parsed=entitySchema.parse(input);
 if(parsed.resource==='waterAdd'){const current=await db.select().from(trackerRecords).where(and(eq(trackerRecords.userId,user.id),eq(trackerRecords.date,input.date))).orderBy(desc(trackerRecords.createdAt)).limit(1);const next=Math.min(15000,Number(current[0]?.data?.amount||0)+parsed.data.amount);if(current[0])await db.update(trackerRecords).set({data:{amount:next}}).where(and(eq(trackerRecords.id,current[0].id),eq(trackerRecords.userId,user.id)));else await db.insert(trackerRecords).values({userId:user.id,date:input.date,data:{amount:next}});return json({ok:true,amount:next});}
 const table=tables[parsed.resource];
 if(parsed.resource==='supplementLog'){const [s]=await db.select().from(supplements).where(and(eq(supplements.id,parsed.data.supplementId),eq(supplements.userId,user.id)));if(!s)throw new ApiError(404,'Supplement not found.');}
 if(input.id){const [row]=await db.update(table).set({data:parsed.data,date:input.date}).where(and(eq(table.id,input.id),eq(table.userId,user.id))).returning();if(!row)throw new ApiError(404,'Entry not found.');return json(row);}
 if(parsed.resource==='schedule'&&parsed.data.supplementId){await db.delete(supplementSchedules).where(and(eq(supplementSchedules.userId,user.id),sql`${supplementSchedules.data}->>'supplementId' = ${parsed.data.supplementId}`));}const [row]=await db.insert(table).values({userId:user.id,date:input.date,data:parsed.data}).returning();
 if(parsed.resource==='supplement'){
   const supplementTime=parsed.data.time;
   const timezone=parsed.data.timezone||'UTC';
   await db.insert(supplementSchedules).values({userId:user.id,date:input.date,data:{name:parsed.data.name,dose:parsed.data.dose,time:supplementTime,timezone,nextAt:new Date().toISOString(),enabled:true,intervalHours:24,supplementId:row.id}}).onConflictDoNothing();
 }
 return json(row,201);
}catch(e){return failure(e);}}
export async function DELETE(req:Request){try{const user=await identity(req);await limit(`write:${user.id}`);const input=await body(req,z.object({resource:z.enum(['food','water','supplement','supplementLog','workout','template','custom','schedule']),id:z.string().uuid()}).strict());const table=input.resource==='food'?foodLogs:tables[input.resource];if(input.resource==='supplement'){await db.delete(supplementLogs).where(and(eq(supplementLogs.userId,user.id),sql`${supplementLogs.data}->>'supplementId' = ${input.id}`));await db.delete(supplementSchedules).where(and(eq(supplementSchedules.userId,user.id),sql`${supplementSchedules.data}->>'supplementId' = ${input.id}`));}const deleted=await db.delete(table).where(and(eq(table.id,input.id),eq(table.userId,user.id))).returning({id:table.id});if(!deleted.length)throw new ApiError(404,'Entry not found.');await audit(user.id,`${input.resource}.deleted`);return json({ok:true});}catch(e){return failure(e);}}
